import { useEffect, useMemo, useRef, useState } from "react";
import { Rich, getInsightObj } from "../utils/text.jsx";
import {
  getCardStyleOverride,
  useDesignAgentUpdate,
} from "../utils/designAgent.js";
import ChatDock from "../components/ChatDock.jsx";
import AnalysisModal from "../components/AnalysisModal.jsx";
import { ChartAiProvider, useChartAi } from "../context/ChartAiContext.jsx";
import ChartAiDrawer from "../components/ChartAiDrawer.jsx";
import {
  DynamicChartRenderer,
  Empty,
  GlobalChartDefs,
} from "../components/CustomChartWidgets.jsx";
import { StoryboardPanel, WhatsNext } from "../components/StoryboardPanel.jsx";
import Template1 from "../dashboards/media_measurement/Template1.jsx";
import Template2 from "../dashboards/media_measurement/Template2.jsx";
import Template3 from "../dashboards/media_measurement/Template3.jsx";
import Template4 from "../dashboards/media_measurement/Template4.jsx";
import Template5 from "../dashboards/media_measurement/Template5.jsx";
import Template6 from "../dashboards/media_measurement/Template6.jsx";
import Template7 from "../dashboards/media_measurement/Template7.jsx";

const DASHBOARD_KEY = "media_measurement";
const BASE_TABS = [
  "Overview",
  "Sentiment Analysis",
  "Themes & Topics",
  "Media Coverage",
  "Key Stories",
];
const DYNAMIC_TAB = "Dynamic Charts";

const TAB_HERO = {
  Overview: {
    label: "The period at a glance",
    lead: "The period,",
    em: "measured end to end.",
    sub: "Coverage volume, reach and sentiment across every tracked source.",
  },
  "Sentiment Analysis": {
    label: "How sentiment moved",
    lead: "The mood of the coverage,",
    em: "day by day.",
    sub: "Positive, neutral and negative split across the period.",
  },
  "Themes & Topics": {
    label: "What drove the conversation",
    lead: "The themes",
    em: "that led the agenda.",
    sub: "Which topics carried the volume — and how they were received.",
  },
  "Media Coverage": {
    label: "Who carried the message",
    lead: "The outlets and authors",
    em: "behind the volume.",
    sub: "Publications, reach and the bylines shaping the story.",
  },
  "Key Stories": {
    label: "The stories that mattered",
    lead: "The standout coverage,",
    em: "good and bad.",
    sub: "The most significant positive, neutral and negative articles.",
  },
  [DYNAMIC_TAB]: {
    label: "On demand",
    lead: "Charts,",
    em: "built on request.",
    sub: "Generated by the data agent from your questions.",
  },
};

function splitHeadline(title) {
  if (!title) return { lead: "", em: "" };
  const m = String(title).match(/^(.*?[.!?])\s+(.+)$/);
  return m ? { lead: m[1], em: m[2] } : { lead: title, em: "" };
}

const SENT = {
  POS: { label: "Positive", color: "#10b981" },
  NEG: { label: "Negative", color: "#ef4444" },
  NEU: { label: "Neutral", color: "#94a3b8" },
};

function nf(n) {
  if (n == null || Number.isNaN(Number(n))) return "—";
  return new Intl.NumberFormat("en-US").format(n);
}

function compact(n) {
  if (n == null || Number.isNaN(Number(n))) return "—";
  return new Intl.NumberFormat("en-US", {
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(n);
}

function fmtDate(d) {
  if (!d) return "";
  const dt = new Date(d);
  if (Number.isNaN(dt.getTime())) return String(d);
  return dt.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

function ChartCard({
  title,
  subtitle,
  insight,
  analysis,
  onOpenAnalysis,
  wide,
  children,
}) {
  useDesignAgentUpdate();
  const cardOverride = getCardStyleOverride(title);
  const cardCustomStyle = cardOverride
    ? {
        background: cardOverride.background_color,
        borderColor: cardOverride.border_color || "rgba(255, 255, 255, 0.25)",
        boxShadow: "0 8px 32px rgba(0, 0, 0, 0.15)",
        color: "#ffffff",
      }
    : undefined;

  return (
    <div
      className={`chartcard${wide ? " chartcard--wide" : ""}`}
      style={cardCustomStyle}
    >
      <div
        className="chartcard__head"
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "flex-start",
        }}
      >
        <div>
          <h3
            className="chartcard__title"
            style={cardOverride ? { color: "#ffffff" } : undefined}
          >
            {title}
          </h3>
          {subtitle && (
            <p
              className="chartcard__sub"
              style={
                cardOverride
                  ? { color: "rgba(255, 255, 255, 0.75)" }
                  : undefined
              }
            >
              {subtitle}
            </p>
          )}
        </div>
        {analysis && (
          <button
            className="tabbtn"
            onClick={onOpenAnalysis}
            style={{
              padding: "6px 12px",
              fontSize: "11.5px",
              fontWeight: 600,
              borderRadius: "8px",
              background: cardOverride
                ? "rgba(255, 255, 255, 0.2)"
                : "rgba(99, 91, 255, 0.12)",
              border: cardOverride
                ? "1px solid rgba(255, 255, 255, 0.3)"
                : "1px solid rgba(99, 91, 255, 0.3)",
              color: cardOverride ? "#ffffff" : "var(--accent-a)",
              cursor: "pointer",
              transition: "background 0.15s, transform 0.1s",
            }}
          >
            ✦ Analysis
          </button>
        )}
      </div>
      <div className="chartcard__body">{children}</div>
      {insight && (
        <p
          className="chartcard__insight"
          style={
            cardOverride
              ? {
                  color: "rgba(255, 255, 255, 0.85)",
                  borderTopColor: "rgba(255, 255, 255, 0.15)",
                }
              : undefined
          }
        >
          <Rich text={insight} />
        </p>
      )}
    </div>
  );
}

function TopArticles({ data }) {
  const cols = ["POS", "NEU", "NEG"];
  const has = cols.some((k) => (data?.[k] || []).length);
  if (!has) return <Empty />;
  return (
    <div className="storiesgrid">
      {cols.map((k) => (
        <div className="storiescol" key={k}>
          <h4 className="storiescol__head" style={{ color: SENT[k].color }}>
            {SENT[k].label}
          </h4>
          {(data?.[k] || []).map((a, i) => (
            <article className="storycard" key={a.id ?? i}>
              <p className="storycard__title">{a.title}</p>
              <p className="storycard__meta">
                {a.domain || "Unknown"} · {fmtDate(a.date)}
                {a.theme ? ` · ${a.theme}` : ""}
              </p>
              <p className="storycard__snippet">{a.content}</p>
            </article>
          ))}
          {(data?.[k] || []).length === 0 && (
            <p className="muted">No articles.</p>
          )}
        </div>
      ))}
    </div>
  );
}

function pickBestFile(videoFiles = []) {
  const mp4 = videoFiles
    .filter((f) => f.file_type === "video/mp4" && f.width <= 1920)
    .sort((a, b) => b.width - a.width);
  return mp4[0]?.link ?? null;
}

function usePexelsVideo(session) {
  const [bgVideoSrc, setBgVideoSrc] = useState();
  const [pexelsVideos, setPexelsVideos] = useState([]);
  const fetchedRef = useRef(false);

  useEffect(() => {
    if (fetchedRef.current) return;
    fetchedRef.current = true;

    const fetchPexelsVideos = async (brandKeyword) => {
      const apiKey = import.meta.env.VITE_PEXELS_API_KEY;
      if (!apiKey) {
        console.warn("[usePexelsVideo] VITE_PEXELS_API_KEY not set in .env");
        return;
      }

      const cleanQuery = (brandKeyword || "business technology")
        .replace(/['"’]/g, "")
        .trim();
      const pexelsBase = import.meta.env.DEV
        ? "/api-pexels"
        : "https://api.pexels.com";
      const url = `${pexelsBase}/videos/search?query=${encodeURIComponent(cleanQuery)}&per_page=15&orientation=landscape&locale=en-US`;

      try {
        const res = await fetch(url, { headers: { Authorization: apiKey } });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const data = await res.json();
        const videos = data.videos ?? [];

        const mp4Links = [];
        for (const video of videos) {
          const link = pickBestFile(video.video_files ?? []);
          if (link && !mp4Links.includes(link)) {
            mp4Links.push(link);
          }
          if (mp4Links.length >= 8) break;
        }

        if (mp4Links.length > 0) {
          setPexelsVideos(mp4Links);
          setBgVideoSrc(mp4Links[0]);
        }
      } catch (err) {
        console.warn("[usePexelsVideo] fetch failed:", err.message);
      }
    };

    const brandKeywords = session?.brand_keywords ?? [];
    console.log({ brandKeywords });

    const query = brandKeywords.length > 0 ? brandKeywords[0] : null;
    fetchPexelsVideos(query);
  }, [session]);

  return { bgVideoSrc, pexelsVideos };
}

import { useOnBackHandler } from "../utils/useOnBackHandler.js";
import { cn } from "../lib/utils";

function MediaMeasurementContent(props) {
  const { isDrawerOpen } = useChartAi();
  const {
    project,
    session,
    chartsData,
    chartsLoading = false,
    chartsError = "",
    onBack,
  } = props;

  useOnBackHandler(onBack);
  const [tab, setTab] = useState("Overview");
  const [modalOpen, setModalOpen] = useState(false);

  useEffect(() => {
    const selectors = [
      ".t7-content",
      '[data-dashboard-template="sense"] .t7-content',
      '[data-dashboard-template="merger"] .content-area',
      ".content-area",
    ];
    selectors.forEach((sel) => {
      const area = document.querySelector(sel);
      if (area && typeof area.scrollTo === "function") {
        area.scrollTo({ top: 0, behavior: "smooth" });
      }
    });
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [tab]);
  const [modalTitle, setModalTitle] = useState("");
  const [modalMarkdown, setModalMarkdown] = useState("");
  const [agentDynamicCharts, setAgentDynamicCharts] = useState([]);

  const dynamicCharts = useMemo(() => {
    const fromBackend =
      chartsData?.dynamic_charts ||
      chartsData?.media_measurement_dynamic_charts ||
      chartsData?.custom_charts ||
      [];
    const list = [
      ...agentDynamicCharts,
      ...(Array.isArray(fromBackend) ? fromBackend : []),
    ];
    const seen = new Set();
    return list.filter((c) => {
      const key = c?.chart_id || c?.title;
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    });
  }, [chartsData, agentDynamicCharts]);

  const LAYOUT_TO_TEMPLATE_MODE = useMemo(
    () => ({
      Classic: "classic",
      Editorial: "editorial",
      Merger: "merger",
      "PR Impact": "impact",
      Glass: "glass",
      Bento: "bento",
      Sense: "sense",
    }),
    [],
  );

  const [templateMode, setTemplateMode] = useState(() => {
    const stored = localStorage.getItem("dashboard_template_mode");
    if (stored && stored !== "gallery") return stored;
    const wf = session?.workflow;
    if (wf && Array.isArray(wf.nodes)) {
      const assemblyNode = wf.nodes.find((n) => n.type === "assembly");
      const layout = assemblyNode?.data?.layout;
      if (layout && LAYOUT_TO_TEMPLATE_MODE[layout]) {
        return LAYOUT_TO_TEMPLATE_MODE[layout];
      }
    }
    return "sense";
  });

  useEffect(() => {
    const syncTemplateMode = () => {
      const stored = localStorage.getItem("dashboard_template_mode");
      if (stored && stored !== "gallery") {
        setTemplateMode(stored);
      } else {
        const wf = session?.workflow;
        if (wf && Array.isArray(wf.nodes)) {
          const assemblyNode = wf.nodes.find((n) => n.type === "assembly");
          const layout = assemblyNode?.data?.layout;
          if (layout && LAYOUT_TO_TEMPLATE_MODE[layout]) {
            const mapped = LAYOUT_TO_TEMPLATE_MODE[layout];
            setTemplateMode(mapped);
            localStorage.setItem("dashboard_template_mode", mapped);
          }
        }
      }
    };

    syncTemplateMode();
    window.addEventListener("storage", syncTemplateMode);
    return () => {
      window.removeEventListener("storage", syncTemplateMode);
    };
  }, [session, LAYOUT_TO_TEMPLATE_MODE]);

  const toggleTemplateMode = (mode) => {
    setTemplateMode(mode);
    localStorage.setItem("dashboard_template_mode", mode);
    window.dispatchEvent(new Event("storage"));
  };

  const TABS = dynamicCharts.length ? [...BASE_TABS, DYNAMIC_TAB] : BASE_TABS;

  function handleAgentCharts(charts) {
    setAgentDynamicCharts((prev) => [...charts, ...prev]);
    setTab(DYNAMIC_TAB);
  }

  const byId = useMemo(() => {
    const arr = chartsData?.[DASHBOARD_KEY];
    const out = {};
    if (Array.isArray(arr))
      arr.forEach((c) => {
        if (c?.chart_id) out[c.chart_id] = c;
      });
    return out;
  }, [chartsData]);

  const insights = chartsData?.chart_insights || {};
  const overall = chartsData?.[`${DASHBOARD_KEY}_overall_summary`] || "";
  const chapters = chartsData?.storyboards?.[DASHBOARD_KEY] || [];
  const chapterFor = (name) =>
    chapters.find((c) => c.tab_name?.toLowerCase() === name.toLowerCase());

  const ins = (id) => getInsightObj(insights, id)?.insight || "";
  const dateIns = (id) => getInsightObj(insights, id)?.date_insights || [];
  const analysisOf = (id) => getInsightObj(insights, id)?.analysis || "";

  const sentiment = byId.sentiment_distribution;
  const coverage = byId.datewise_coverage;
  const theme = byId.theme_distribution;
  const syndication = byId.original_vs_syndicated;
  const totalCount = byId.total_count?.data?.total_count;
  const totalReach = byId.total_reach?.data?.total_reach;

  const posPct = (() => {
    const s = sentiment?.data;
    const pos = s?.POS?.count || 0;
    const denom =
      totalCount ||
      (s?.POS?.count || 0) + (s?.NEG?.count || 0) + (s?.NEU?.count || 0);
    return denom ? Math.round((pos / denom) * 100) : 0;
  })();

  const heroFor = (name) => {
    if (name === "Overview") {
      const ch = chapterFor("Overview");
      return {
        kicker: `Media Measurement · ${ch?.section_label || TAB_HERO.Overview.label}`,
        lead: `${nf(totalCount)} articles.`,
        em: `${posPct}% ran positive.`,
        sub: ch?.description || TAB_HERO.Overview.sub,
      };
    }
    const ch = chapterFor(name);
    if (ch && (ch.title || ch.description)) {
      const { lead, em } = splitHeadline(ch.title);
      return {
        kicker: `Media Measurement · ${ch.section_label || TAB_HERO[name]?.label || name}`,
        lead: lead || TAB_HERO[name]?.lead || name,
        em: em || TAB_HERO[name]?.em || "",
        sub: ch.description || TAB_HERO[name]?.sub || "",
      };
    }
    const f = TAB_HERO[name] || { label: name, lead: name, em: "", sub: "" };
    return {
      kicker: `Media Measurement · ${f.label}`,
      lead: f.lead,
      em: f.em,
      sub: f.sub,
    };
  };
  const hero = heroFor(tab);

  const { bgVideoSrc, pexelsVideos } = usePexelsVideo(session);

  const activeVideoSrc = useMemo(() => {
    if (!pexelsVideos || pexelsVideos.length === 0) return bgVideoSrc || null;
    const tabIndex = TABS.indexOf(tab);
    if (tabIndex === -1) return pexelsVideos[0];
    return pexelsVideos[tabIndex % pexelsVideos.length];
  }, [pexelsVideos, TABS, tab, bgVideoSrc]);

  const stats = useMemo(
    () => [
      { n: nf(totalCount), l: "Total articles" },
      { n: compact(totalReach), l: "Total reach" },
      { n: sentiment?.data?.net_sentiment_score ?? "—", l: "Net sentiment" },
    ],
    [totalCount, totalReach, sentiment],
  );

  const virtualReport = useMemo(() => {
    const s = sentiment?.data;
    if (!s) return null;
    const pos = s.POS?.count || 0;
    const neu = s.NEU?.count || 0;
    const neg = s.NEG?.count || 0;
    const total = pos + neu + neg;
    if (total === 0) return null;
    return {
      day: "Measurement Period",
      date: "Overall Sentiment Split",
      total,
      pos,
      neut: neu,
      neg,
    };
  }, [sentiment]);

  const openAnalysis = (chartId, title) => {
    setModalTitle(title);
    setModalMarkdown(analysisOf(chartId));
    setModalOpen(true);
  };

  // ── Transform sentiment_over_time data ──
  const formattedSentimentOverTimeChart = useMemo(() => {
    const chart = byId.sentiment_distribution;
    if (!chart) return null;
    const datewise = chart.data?.datewise_distribution || {};
    const rows = Object.entries(datewise)
      .map(([date, v]) => ({
        date,
        POS: v.POS || 0,
        NEG: v.NEG || 0,
        NEU: v.NEU || 0,
      }))
      .sort((a, b) => a.date.localeCompare(b.date));
    return {
      chart_id: "sentiment_over_time",
      chart_type: "stacked_area",
      title: "Sentiment Over Time",
      description: "Daily positive / neutral / negative coverage split.",
      data: rows,
      series: ["POS", "NEU", "NEG"],
    };
  }, [byId]);

  // ── Transform theme_distribution data ──
  const formattedThemeChart = useMemo(() => {
    const chart = byId.theme_distribution;
    if (!chart) return null;
    const rows = (chart.data || []).map((d) => ({
      theme: d.theme,
      POS: d.sentiments?.POS || 0,
      NEG: d.sentiments?.NEG || 0,
      NEU: d.sentiments?.NEU || 0,
    }));
    return {
      ...chart,
      chart_type: "stacked_bar",
      data: rows,
      series: ["POS", "NEU", "NEG"],
    };
  }, [byId]);

  // ── Transform original_vs_syndicated data ──
  const formattedSyndicationChart = useMemo(() => {
    const chart = byId.original_vs_syndicated;
    if (!chart) return null;
    const data = chart.data || {};
    const rows = [
      { name: "Original", value: data?.original?.count || 0 },
      { name: "Syndicated", value: data?.syndicated?.count || 0 },
    ].filter((r) => r?.value > 0);
    return {
      ...chart,
      chart_type: "donut",
      data: rows,
    };
  }, [byId]);

  // ── Transform publication_reach_sentiment data ──
  const formattedReachSentimentChart = useMemo(() => {
    const chart = byId.publication_reach_sentiment;

    if (!chart) return null;
    const rows = (chart.data || []).map((d) => ({
      ...d,
      total_reach: Number(d.total_reach ?? d.x ?? 0),
      net_sentiment: Number(d.net_sentiment ?? d.y ?? 0),
      total_count: Number(d.total_count ?? d.z ?? 1),
      x: Number(d.total_reach ?? d.x ?? 0),
      y: Number(d.net_sentiment ?? d.y ?? 0),
      z: Number(d.total_count ?? d.z ?? 1),
      label: d.label ?? d.name ?? "",
    }));
    return {
      ...chart,
      chart_type: "scatter",
      data: rows,
      series: ["total_reach", "net_sentiment", "total_count"],
    };
  }, [byId]);

  if (chartsLoading) {
    return (
      <div className="state">
        <span className="loader" />
        <p>Loading dashboard…</p>
      </div>
    );
  }
  if (chartsError) {
    return (
      <div className={cn("state", "state--error")}>
        <p>{chartsError}</p>
      </div>
    );
  }

  return (
    <div
      style={{
        marginRight: isDrawerOpen ? "420px" : "0px",
        transition: "margin-right 0.35s cubic-bezier(0.16, 1, 0.3, 1)",
      }}
    >
      {/* Shared SVG gradient definitions for all charts on this page */}
      <GlobalChartDefs />
      {onBack && templateMode === "classic" && (
        <div
          style={{
            position: "relative",
            zIndex: 1000,
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            padding:
              templateMode === "merger" ? "14px 28px 14px 296px" : "14px 28px",
            background:
              templateMode === "editorial" || templateMode === "merger"
                ? "var(--wine-page-bg)"
                : "",
            borderBottom:
              templateMode === "editorial" || templateMode === "merger"
                ? "1px solid var(--wine-border-light)"
                : "none",
            marginBottom:
              templateMode === "editorial" || templateMode === "merger"
                ? 0
                : -50,
          }}
        >
          <button
            onClick={onBack}
            style={{
              background:
                templateMode === "editorial" || templateMode === "merger"
                  ? "#fff"
                  : "rgba(0, 0, 0, 1)",
              backdropFilter: "blur(12px)",
              WebkitBackdropFilter: "blur(12px)",
              border:
                templateMode === "editorial" || templateMode === "merger"
                  ? "1px solid var(--wine-border)"
                  : "1px solid rgba(255,255,255,0.15)",
              color:
                templateMode === "editorial" || templateMode === "merger"
                  ? "var(--wine-primary)"
                  : "rgba(255, 255, 255, 0.8)",
              borderRadius: 20,
              padding: "6px 14px",
              fontSize: 12,
              fontWeight: 600,
              cursor: "pointer",
              display: "flex",
              alignItems: "center",
              gap: 6,
              fontFamily: "Inter, SF Pro Display, sans-serif",
              transition: "background 0.2s, color 0.2s",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background =
                templateMode === "editorial" || templateMode === "merger"
                  ? "var(--wine-border-light)"
                  : "rgba(255,255,255,0.16)";
              e.currentTarget.style.color =
                templateMode === "editorial" || templateMode === "merger"
                  ? "var(--wine-primary)"
                  : "#fff";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background =
                templateMode === "editorial" || templateMode === "merger"
                  ? "#fff"
                  : "rgba(0, 0, 0, 1)";
              e.currentTarget.style.color =
                templateMode === "editorial" || templateMode === "merger"
                  ? "var(--wine-primary)"
                  : "rgba(255,255,255,0.8)";
            }}
          >
            ← Back to dashboards
          </button>
          <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
            <button
              className={`template-mode-btn ${templateMode === "classic" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("classic")}
              style={{
                background:
                  templateMode === "editorial" || templateMode === "merger"
                    ? templateMode === "classic"
                      ? "var(--wine-primary)"
                      : "#fff"
                    : undefined,
                color:
                  templateMode === "editorial" || templateMode === "merger"
                    ? templateMode === "classic"
                      ? "#fff"
                      : "#1C2B3A"
                    : undefined,
                borderColor:
                  templateMode === "editorial" || templateMode === "merger"
                    ? "var(--wine-border)"
                    : undefined,
              }}
            >
              <span className="tmb-dot" /> Classic
            </button>
            <button
              className={`template-mode-btn ${templateMode === "editorial" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("editorial")}
              style={{
                background:
                  templateMode === "editorial" || templateMode === "merger"
                    ? templateMode === "editorial"
                      ? "var(--wine-primary)"
                      : "#fff"
                    : undefined,
                color:
                  templateMode === "editorial" || templateMode === "merger"
                    ? templateMode === "editorial"
                      ? "#fff"
                      : "#1C2B3A"
                    : undefined,
                borderColor:
                  templateMode === "editorial" || templateMode === "merger"
                    ? "var(--wine-border)"
                    : undefined,
              }}
            >
              <span className="tmb-dot" /> Editorial
            </button>
            <button
              className={`template-mode-btn ${templateMode === "merger" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("merger")}
              style={{
                background:
                  templateMode === "editorial" || templateMode === "merger"
                    ? templateMode === "merger"
                      ? "var(--wine-primary)"
                      : "#fff"
                    : undefined,
                color:
                  templateMode === "editorial" || templateMode === "merger"
                    ? templateMode === "merger"
                      ? "#fff"
                      : "#1C2B3A"
                    : undefined,
                borderColor:
                  templateMode === "editorial" || templateMode === "merger"
                    ? "var(--wine-border)"
                    : undefined,
              }}
            >
              <span className="tmb-dot" /> Merger
            </button>
            <button
              className={`template-mode-btn ${templateMode === "impact" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("impact")}
            >
              <span className="tmb-dot" /> PR Impact
            </button>
            <button
              className={`template-mode-btn ${templateMode === "glass" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("glass")}
            >
              <span className="tmb-dot" /> Glass
            </button>
            <button
              className={`template-mode-btn ${templateMode === "bento" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("bento")}
            >
              <span className="tmb-dot" /> Bento
            </button>
            <button
              className={`template-mode-btn ${templateMode === "sense" ? "active" : ""}`}
              onClick={() => toggleTemplateMode("sense")}
            >
              <span className="tmb-dot" /> Sense
            </button>
          </div>
        </div>
      )}

      {templateMode === "sense" ? (
        <Template7
          templateMode={templateMode}
          onChangeTemplate={toggleTemplateMode}
          onBack={onBack}
          project={project}
          session={session}
          chartsData={chartsData}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
        />
      ) : templateMode === "bento" ? (
        <Template6
          templateMode={templateMode}
          onChangeTemplate={toggleTemplateMode}
          onBack={onBack}
          project={project}
          session={session}
          chartsData={chartsData}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
        />
      ) : templateMode === "glass" ? (
        <Template5
          templateMode={templateMode}
          onChangeTemplate={toggleTemplateMode}
          onBack={onBack}
          project={project}
          session={session}
          chartsData={chartsData}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
        />
      ) : templateMode === "impact" ? (
        <Template4
          templateMode={templateMode}
          onChangeTemplate={toggleTemplateMode}
          onBack={onBack}
          project={project}
          session={session}
          chartsData={chartsData}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
        />
      ) : templateMode === "editorial" ? (
        <Template2
          templateMode={templateMode}
          onChangeTemplate={toggleTemplateMode}
          onBack={onBack}
          project={project}
          session={session}
          chartsData={chartsData}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
        />
      ) : templateMode === "merger" ? (
        <Template3
          templateMode={templateMode}
          onChangeTemplate={toggleTemplateMode}
          onBack={onBack}
          project={project}
          session={session}
          chartsData={chartsData}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
        />
      ) : (
        <Template1
          project={project}
          session={session}
          tab={tab}
          setTab={setTab}
          openAnalysis={openAnalysis}
          chapterFor={chapterFor}
          chapters={chapters}
          DASHBOARD_KEY={DASHBOARD_KEY}
          DYNAMIC_TAB={DYNAMIC_TAB}
          dynamicCharts={dynamicCharts}
          byId={byId}
          insights={insights}
          overall={overall}
          ins={ins}
          dateIns={dateIns}
          analysisOf={analysisOf}
          sentiment={sentiment}
          coverage={coverage}
          theme={theme}
          syndication={syndication}
          totalCount={totalCount}
          totalReach={totalReach}
          formattedThemeChart={formattedThemeChart}
          formattedSyndicationChart={formattedSyndicationChart}
          formattedReachSentimentChart={formattedReachSentimentChart}
          formattedSentimentOverTimeChart={formattedSentimentOverTimeChart}
          activeVideoSrc={activeVideoSrc}
          hero={hero}
          TABS={TABS}
          stats={stats}
          virtualReport={virtualReport}
        />
      )}

      <AnalysisModal
        open={modalOpen}
        title={modalTitle}
        markdown={modalMarkdown}
        onClose={() => setModalOpen(false)}
      />

      <ChatDock
        sessionId={session?.id}
        mode="route"
        onCharts={handleAgentCharts}
        chartsData={chartsData}
        dashboardKey="media_measurement"
        project={project}
        session={session}
      />
    </div>
  );
}

export default function MediaMeasurementScreen(props) {
  return (
    <ChartAiProvider>
      <MediaMeasurementContent {...props} />
      <ChartAiDrawer sessionId={props.session?.id} />
    </ChartAiProvider>
  );
}
